name: Generate Routeviews ASN database
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
    routeviews-asn-generator:
        permissions:
          contents: write
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download Routeviews ASN database
              run: |
                wget https://raw.githubusercontent.com/sapics/ip-location-db/refs/heads/main/asn/asn-ipv4.csv
                wget https://raw.githubusercontent.com/sapics/ip-location-db/refs/heads/main/asn/asn-ipv6.csv

            - name: Create ASN database
              run: |
                sqlite3 asns.sqlite "
                CREATE TABLE ipv4 (
                  start_ip TEXT NOT NULL,
                  end_ip TEXT NOT NULL,
                  asn INTEGER NOT NULL,
                  organization TEXT NOT NULL
                );

                CREATE TABLE ipv6 (
                  start_ip TEXT NOT NULL,
                  end_ip TEXT NOT NULL,
                  asn INTEGER NOT NULL,
                  organization TEXT NOT NULL
                );

                CREATE INDEX idx_asn_ipv4 ON ipv4 (asn);
                CREATE INDEX idx_asn_ipv6 ON ipv6 (asn);
                CREATE INDEX idx_asn_ipv4_organization ON ipv4 (organization);
                CREATE INDEX idx_asn_ipv6_organization ON ipv6 (organization);
                "

            - name: Populate ASN database with IPv4 data
              run: |
                sqlite3 asns.sqlite ".mode csv" ".import asn-ipv4.csv ipv4"

            - name: Populate ASN database with IPv6 data
              run: |
                sqlite3 asns.sqlite ".mode csv" ".import asn-ipv6.csv ipv6"

            - name: Move to routeviews database directory
              run: |
                rm -rf app-modules/routeviews-integration/database/asns.sqlite
                mv asns.sqlite app-modules/routeviews-integration/database/

            - name: Clean up CSV files
              run: |
                rm asn-ipv4.csv
                rm asn-ipv6.csv

            - name: Create a pull request
              uses: peter-evans/create-pull-request@v7
              with:
                branch: update-routeviews-asn-db
                title: "Update Routeview ASN database"
                commit-message: "update routeview asn database"
                base: main


